---
version: '2'
services:
  app:
    image: zolrath/phoenix:1.5.1
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:12.2
